name: Ensure pre_main contains main's latest commit

on:
  push:
    branches:
      - pre_main
  pull_request:
    branches:
      - main

jobs:
  check-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: pre_main
          fetch-depth: 0 # Fetch full history for commit checks

      - name: Fetch main branch
        run: git fetch origin main

      - name: Get latest main commit
        id: main-commit
        run: |
          main_sha=$(git rev-parse origin/main)
          echo "main_sha=${main_sha}" >> $GITHUB_OUTPUT
          echo "Latest main commit: ${main_sha}"

      - name: Verify pre_main contains main's commit
        run: |
          if ! git merge-base --is-ancestor "${{ steps.main-commit.outputs.main_sha }}" HEAD; then
            echo "::error::pre_main is missing main's latest commit (${{ steps.main-commit.outputs.main_sha }})"
            echo "Please merge main into pre_main:"
            echo "  git checkout pre_main"
            echo "  git merge main"
            echo "  git push origin pre_main"
            exit 1
          else
            echo "✓ pre_main contains main's latest commit"
          fi
