# .github/workflows/check-sync.yml
name: Ensure pre_main is up to date with main

on:
  push:
    branches:
      - pre_main
  pull_request:
    branches:
      - main
      
jobs:
  check-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Fetch main branch
        run: git fetch origin main

      - name: Check if main is ancestor of this branch
        run: |
          git fetch origin main
          git merge-base --is-ancestor origin/main HEAD || {
            echo "❌ This branch is not up to date with main. Please merge or rebase main into your branch.";
            exit 1;
          }
